#!/bin/bash

if [[ $1 == install || update ]]; then
    echo "" > /fs/jb/usr/libexec/afc2dSupport
    chmod 777 /fs/jb/usr/libexec/afc2dSupport
    
    chown root:wheel /fs/jb/usr/bin/killdaemon
    chmod 6755 /fs/jb/usr/bin/killdaemon
fi

exit 0
